import type { Metadata } from "next";
import React from "react";
import "./globals.css";

// Import styles of packages that you've installed.
// All packages except `@mantine/hooks` require styles imports
import "@mantine/core/styles.css";
import {
  AppShell,
  AppShellMain,
  Text,
  Box,
  ColorSchemeScript,
  MantineProvider,
} from "@mantine/core";
import { NavbarSimple } from "@/app/components/NavbarSimple";
import HumanFriendlyColumn from "@/app/components/HumanFriendlyColumn";

export const metadata: Metadata = {
  title: "Parliament Summary",
};

function Shell({ children }: { children: React.ReactNode }) {
  return (
    <AppShell
      // navbar={{
      //   width: 300,
      //   breakpoint: "sm",
      // }}
      padding="md"
    >
      {/*<AppShellNavbar p="md">*/}
      {/*  <NavbarSimple />*/}
      {/*</AppShellNavbar>*/}

      <AppShellMain>{children}</AppShellMain>

      <Box mt="xl" mb="xl" component="footer">
        <HumanFriendlyColumn>
          <Text mt="xs" c="dimmed">
            Disclaimer:
            <br />
            <br />
            The information provided on this webpage is intended for reference
            purposes only. The summaries are generated by artificial
            intelligence and should not be regarded as fully accurate or
            comprehensive. The data is sourced exclusively from publicly
            available parliamentary sources online such as parliament.gov.sg.
            Users are advised to consult original parliamentary documents and
            official records for precise and authoritative information.
          </Text>
        </HumanFriendlyColumn>
      </Box>
    </AppShell>
  );
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const defaultColorScheme = "auto";

  // noinspection HtmlRequiredTitleElement
  return (
    <html lang="en">
      <head>
        <ColorSchemeScript defaultColorScheme={defaultColorScheme} />
      </head>
      <body>
        <MantineProvider defaultColorScheme={defaultColorScheme}>
          <Shell>{children}</Shell>
        </MantineProvider>
      </body>
    </html>
  );
}
